### ISSUE TITLE
Don't do anything unusual to build portable or non-portable builds

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1045]
Currently source-build uses patches and extra properties to be able to build both portable and non-portable SDKs.
Final goal:
- [ ] All repos that can change portableness supply one easy way to choose portable or non-portable build.
- [ ] Source-build supports both portable and non-portable builds on all applicable platforms.
- [ ] It does this uses only the standard build switches for each repository, no extra properties or patches.
- [ ] Portableness is specified explicitly in all cases where it applies.
- [ ] "No extra properties" includes not specifying RIDs, whether for "which packages to download" or "which packages to produce".
    - [ ] This means we can eliminate our dependency on `RuntimeEnvironment` checks to determine a RID before the build runs.
- [ ] Source-build can build both portable and non-portable builds using either a portable (probably official) SDK or a non-portable (probably source-built) SDK.

Related: #696, #660, #750.

**Comment by MichaelSimons** [comment]
[Triage] Closing in favor of https://github.com/dotnet/source-build/issues/2932.
