### ISSUE TITLE
Source-build can consume and aggregate constituent repo builds uniformly

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#145]
Objective: Source-build can automatically produce community and Red Hat source-builds with no special intervention (patches are eliminated for repos). Builds are still vertical for each platform Window, MacOS, Linux.

- [ ] submodule patches are removed
   - [ ] auto-dependency flow is working across submodule builds
- [ ] All supported vertical source-builds are running
- [ ] Prodcon build output SHAs are updated to source-build automatically
- [ ] Toolset for source-build is bounded, any new toolset brought in by submodules should break source-build
- [x] CI on Red Hat tarball protects that deliverable
- [ ] Source-build build status is reported as a peer to prodcon builds
