### ISSUE TITLE
Mono and .NET source-build are cohesive

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#1471]
- [ ] Customer understand release cadences and support matrix differences
- [ ] Distros maintainers understand release cadences and support matrix differences

Potential engineering:

- [ ] composition of source-built Mono and source-built .NET SDK

**Comment by omajid** [comment]
For what it's worth, if the last item means to produce a .NET SDK using the mono runtime, we have that working for .NET 6 on s390x.

**Comment by MichaelSimons** [comment]
[Triage] Mono is source-buildable as @omajid notes.  The original issue description is not clear on the intent.  Closing.
