### ISSUE TITLE
.NET 8: Tracking issue for repos specifying and regularly updating their dependencies.

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#2980]
### Description

This is a repo tracking issue related to https://github.com/dotnet/source-build/issues/2979. Repositories should:
- Specify all dependencies produced by source-built repositories in their `eng/Version.Details.xml` files. They need only specify dependencies for repos that are produced **earlier** in source build.

They should then either:
- Add dependency flow that regularly updates these dependencies to latest **or**
- Pin these dependencies and provide justification as to why these should not be updated. These cases will require a new reference package be added to https://github.com/dotnet/source-build-reference-packages.

### Repositories

- [ ] https://github.com/dotnet/arcade/issues/10576
- [ ] https://github.com/dotnet/aspnetcore/issues/43530
- [ ] https://github.com/dotnet/command-line-api/issues/1825
- [ ] https://github.com/dotnet/deployment-tools/issues/215
- [ ] https://github.com/dotnet/diagnostics/issues/3326
- [ ] https://github.com/dotnet/format/issues/1699
- [ ] https://github.com/dotnet/fsharp/issues/13804
- [ ] https://github.com/dotnet/installer/issues/14415
- [ ] https://github.com/dotnet/linker/issues/3007
- [ ] https://github.com/dotnet/runtime/issues/74764
- [ ] https://github.com/dotnet/msbuild/issues/7921
- [ ] https://github.com/NuGet/Home/issues/12061
- [ ] https://github.com/dotnet/razor-tooling/issues/7073
- [ ] https://github.com/dotnet/roslyn-analyzers/issues/6131
- [ ] https://github.com/dotnet/roslyn/issues/63645
- [ ] https://github.com/dotnet/runtime/issues/74765
- [ ] https://github.com/dotnet/sdk/issues/27532
- [ ] https://github.com/dotnet/sourcelink/issues/864
- [ ] https://github.com/dotnet/symreader/issues/264
- [ ] https://github.com/dotnet/templating/issues/5177
- [ ] https://github.com/dotnet/test-templates/issues/245
- [ ] https://github.com/microsoft/vstest/issues/3980
- [x] https://github.com/dotnet/xdt/issues/461
- [ ] https://github.com/dotnet/xliff-tasks/issues/660

**Comment by mmitche** [comment]
@MichaelSimons is this assertion correct?

> They need only specify dependencies for repos that are produced earlier in source build

**Comment by MichaelSimons** [comment]
>They need only specify dependencies for repos that are produced earlier in source build

To avoid confusion, it is really for any dependencies produced in source-build.  Because there a cycles in the graph, a dependency could be built after.  In that case, the dependency gets satisfied by previous source-built artifacts.  Even if that is the case, we are building with a recent version and we would like to avoid pinned references in those cases.

**Comment by mmitche** [comment]
> > They need only specify dependencies for repos that are produced earlier in source build
> 
> To avoid confusion, it is really for any dependencies produced in source-build. Because there a cycles in the graph, a dependency could be built after. In that case, the dependency gets satisfied by previous source-built artifacts. Even if that is the case, we are building with a recent version and we would like to avoid pinned references in those cases.

We do need to avoid product dependency cycles in order to not break the current official build and staging process. We can have cycles for toolset dependencies, but not for product dependencies. Do you have an example of one of these that exists today that we can analyze a bit?

**Comment by mmitche** [comment]
@MichaelSimons I believe I have all the child issues opened for this work

**Comment by MichaelSimons** [comment]
@mmitche - I believe this was done as part of https://github.com/dotnet/source-build/issues/3043.  Can this and all related issues be closed?

**Comment by mmitche** [comment]
Yep, that and the prebuilt detection work.
