### ISSUE TITLE
.NET 8: Tracking for TFM trimming, and elimination of net4* targeting in Linux source-build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3014]
### Description

Tracking for https://github.com/dotnet/source-build/issues/2901. **Requires** https://github.com/dotnet/source-build/issues/3013. source-build net4* targeting elimination required https://github.com/dotnet/source-build/issues/2974

The purpose of this operation is twofold:
- [ ] Reduce the number of TFMs present overall in .NET's build, potentially improving build time.
- [ ] Eliminate framework TFMs, drastically reducing the size of the source build repository size.

When TFMs other than the latest .NET Core TFM are targeted in source-build, the reference assets for that TFM must be provided via a source build reference package. This is a 'text only' package that is assembled from IL at the beginning of the build to satisfy the required reference assets. In Microsoft's build, these would be restored from the internet, but in source build this is not allowed.

These SBRPs are large. All told, the total size contribution for just the netframework 4* TFMs is around 3GB. Not only does this have a significant contribution to the source build repo size, but it also affects build time. For Linux source build, we spend large amounts of time building assets that are simply thrown away at the end.

An 'ideal' would be a single TFM used throughout all of the .NET build, source build or otherwise. This is not possible. There are legitimate reasons to target older TFMs, especially netstandard. However, we should be able to justify each additional TFM.

To complete this work, repositories will use the tooling provided via https://github.com/dotnet/source-build/issues/2901 to identify the TFMs in use in their repository. For each TFM, they should do the following:
- [ ] If the TFM can be eliminated, or upgraded to latest (e.g. target the latest netcore explicitly, or use net472), do so. netframework TFM removal for tools and internal code is likely low hanging fruit.
- [ ] **Requires https://github.com/dotnet/source-build/issues/2974** If the TFM is a framework TFM, it should be conditionalized out in source build for Linux.

It is a goal that the form of this conditionalization remain consistent across projects, and used relatively sparingly. How this conditionalization should be done will be designed in https://github.com/dotnet/source-build/issues/2974

### Repositories

- [x] https://github.com/dotnet/arcade/issues/10721
- [x] https://github.com/dotnet/aspnetcore/issues/43696
- [x] https://github.com/dotnet/runtime/issues/83991
- [x] https://github.com/dotnet/command-line-api/issues/1834
- [x] https://github.com/dotnet/deployment-tools/issues/217
- [x] https://github.com/dotnet/diagnostics/issues/3341
- [x] https://github.com/dotnet/runtime/issues/83278
- [x] https://github.com/dotnet/format/issues/1711
- [x] https://github.com/dotnet/fsharp/issues/13829
- [x] https://github.com/dotnet/installer/issues/14434
- [x] https://github.com/dotnet/linker/issues/3016
- [x] https://github.com/dotnet/runtime/issues/74950
- [x] https://github.com/dotnet/msbuild/issues/7936
- [x] https://github.com/NuGet/Home/issues/12074
- [x] https://github.com/dotnet/razor/issues/7071
- [x] https://github.com/dotnet/roslyn-analyzers/issues/6144
- [x] https://github.com/dotnet/roslyn/issues/63746
- [x] https://github.com/dotnet/sdk/issues/27642
- [x] https://github.com/dotnet/sourcelink/issues/868
- [x] https://github.com/dotnet/symreader/issues/266
- [x] https://github.com/dotnet/templating/issues/5192
- [x] https://github.com/dotnet/test-templates/issues/248
- [x] https://github.com/microsoft/vstest/issues/3989
- [x] https://github.com/dotnet/xdt/issues/464
- [x] https://github.com/dotnet/xliff-tasks/issues/663

**Comment by mmitche** [comment]
@MichaelSimons Here is the bones of the tracking issue I'm going to open in the repos, can you take a look?

@ericstj For non-source-build cases where we need to target netframework, **and** any netframework TFM will do, is there a preferred TFM? I'm mostly thinking of non-shipping packages or tooling, as this would be a breaking change otherwise.

**Comment by ericstj** [comment]
> For non-source-build cases where we need to target netframework, and any netframework TFM will do, is there a preferred TFM

In dotnet/runtime we have a preference for libraries - the minimum last supported framework which we define as [NetFrameworkMinimum](https://github.com/dotnet/runtime/blob/209c040d261558d6d58ebf046e39491b22fb28f1/Directory.Build.props#L69).  There is likely a different preference for things that are part of VS and that's whatever VS's pre-requisite framework is.  I'm not certain what that is, but I do see the SDK targeting [net472](https://github.com/dotnet/sdk/blob/40f1676a94b6b1cbb3dbe04839532819e7b9a443/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj#L15).  cc @marcpopMSFT @ViktorHofer

**Comment by ViktorHofer** [comment]
In dotnet/runtime, all libraries target `NetCoreAppCurrent` and that refers to the .NETCoreApp version currently being developed. Packages target additional frameworks like net6.0, net7.0, net462, netstandard2.0 and netstandard2.1.

IMHO if feasible, for source build, we should only build `NetCoreAppCurrent`. In dotnet/runtime we already support building just a slice of the graph but as NuGet still restores all target frameworks we would need to rewrite the `TargetFrameworks` property to trim the other frameworks out.

**Comment by mmitche** [comment]
> IMHO if feasible, for source build, we should only build NetCoreAppCurrent. In dotnet/runtime we already support building just a slice of the graph but as NuGet still restores all target frameworks we would need to rewrite the TargetFrameworks property to trim the other frameworks out.

What about internal tooling or non-shipping packages? Do we have any cases where we are building framework bits in runtime today?

It would be awesome to code up the TargetFrameworks properties in such a way that it's globally overridable on the runtime side. It is less ideal to have a ton of conditionals in every project.

**Comment by mmitche** [comment]
> Yes, we have msbuild tasks that target .NET Framework but those target .NETCoreApp as well. For source build I guess it's OK to not build the .NET Framework msbuild tasks.
> 
> >

Do you think that the framework tasks are still required at all?

> That said, the feasibility question regarding repositories only relying on $(NetCoreAppCurrent) assets still stands. We in dotnet/runtime are technically able to only produce $(NetCoreAppCurrent) assemblies and packages but if dependent repositories require other target frameworks like net6.0 or .NETStandard then this wouldn't work.

I think we should keep netstandard where we actually want to release a package as netstandard. Downstream repos should not be targeting net6 (for various reasons) in source build. Those binaries going to be running on a net7 runtime, regardless of whether they want net6 or not.

**Comment by ViktorHofer** [comment]
> I think we should keep netstandard where we actually want to release a package as netstandard. 

How many of those packages do we have? As .NETStandard's public api surface is limited I noticed that many/most packages that offer a .NETStandard asset, multi-target to benefit from newer .NETCoreApp features. I would be surprised if we have many packages that are .NETStandard only. It might make sense for the stack to always target the very latest. (That's what we do in runtime).

> Do you think that the framework tasks are still required at all?

They should not be required. Also FWIW msbuild was considering making it possible to load .NETCoreApp tasks in the .NET Framework version of msbuild and inside VS so that we can remove the .NETFramework task variants.

**Comment by mmitche** [comment]
> How many of those packages do we have? As .NETStandard's public api surface is limited I noticed that many/most packages that offer a .NETStandard asset, multi-target to benefit from newer .NETCoreApp features. I would be surprised if we have many packages that are .NETStandard only. It might make sense for the stack to always target the very latest. (That's what we do in runtime).

Roger that. At least we need a way to evaluate what we are producing and then we can make decisions.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - What work remains here?  Can this be closed?
