### ISSUE TITLE
[VMR] Component Governance errors tracking

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3152]
### ⚠️ NuGet Feed Configuration
- [x] [fsharp/tests/FSharp.Build.UnitTests/NuGet.Config](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_git/ddda0dd6-918f-48ba-ba8f-730d9d8c9320?path=%2Fsrc%2Ffsharp%2Ftests%2FFSharp.Build.UnitTests%2FNuGet.Config&_a=annotate)
- [x] [sdk/src/Assets/NonRestoredTestProjects/AppThrowingException/AppDependingOnOtherAsTool/NuGet.Config](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_git/ddda0dd6-918f-48ba-ba8f-730d9d8c9320?path=%2Fsrc%2Fsdk%2Fsrc%2FAssets%2FNonRestoredTestProjects%2FAppThrowingException%2FAppDependingOnOtherAsTool%2FNuGet.Config&_a=annotate)
- [x] [sdk/src/Assets/TestProjects/TrimmedAppWithReferences/App/nuget.config](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_git/ddda0dd6-918f-48ba-ba8f-730d9d8c9320?path=%2Fsrc%2Fsdk%2Fsrc%2FAssets%2FTestProjects%2FTrimmedAppWithReferences%2FApp%2Fnuget.config&_a=annotate)
- [x] [sdk/src/Assets/TestProjects/PackageValidationTestProject/NuGet.Config](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_git/ddda0dd6-918f-48ba-ba8f-730d9d8c9320?path=%2Fsrc%2Fsdk%2Fsrc%2FAssets%2FTestProjects%2FPackageValidationTestProject%2FNuGet.Config&_a=annotate)

### ⚠️ [NuGet security analysis](https://docs.opensource.microsoft.com/tools/cg/how-to/nuget-multifeed-configuration/) - Potential upstreams in a feed

> Seems like there might be a feed it cannot access so it cannot decide whether it has upstreams (and potentially leads to `nuget.org`)

- [x] [nuget-client/Nuget.Config](https://github.com/NuGet/NuGet.Client/blob/5818ca051867f60dffa45dd161e316e2d1c916b7/NuGet.Config#L7)

Plus there are more but once we sync the removal of `FileSystem` and `Common` submodules, they will go away.

### ⚠️ [CFS0013](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/project-artemis/central-feed-services-cfs#5-cfs0013---nugetconfig-files-have-feeds-that-are-not-azure-artifacts) - Package source has value that is not an Azure Artifacts feed

> Usually, these usually have `nuget.org` inside. I am not sure how this ties to https://github.com/dotnet/source-build/issues/3170

- [ ] [format/tests/projects/for_analyzer_formatter/analyzer_project/NuGet.config](https://github.com/dotnet/format/blob/main/tests/projects/for_analyzer_formatter/analyzer_project/NuGet.config)
- [ ] [nuget-client/test/EndToEnd/NuGet.Config](https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/NuGet.Config)
- [ ] [sdk/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/nuget.config](https://github.com/dotnet/sdk/blob/main/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/nuget.config)  
    _I think this one needs an exemption as it's a template for new projects_ 
- [x] [source-build-externals/src/application-insights/BASE/NuGet.config](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/51c3ed8aa3f32209edf01168f9136a3ac8486c5d/BASE/NuGet.config)
- [x] [source-build-externals/src/application-insights/NETCORE/NuGet.config](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/51c3ed8aa3f32209edf01168f9136a3ac8486c5d/NETCORE/NuGet.config)
- [x] [source-build-externals/src/application-insights/NuGet.config](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/51c3ed8aa3f32209edf01168f9136a3ac8486c5d/NuGet.config)
- [x] [source-build-externals/src/newtonsoft-json/Src/NuGet.Config](https://github.com/JamesNK/Newtonsoft.Json/tree/ae9fe44e1323e91bcbd185ca1a14099fba7c021f/Src/NuGet.Config)

### ⚠️ [CFS0011](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/project-artemis/central-feed-services-cfs#3-cfs0011---c-projects-are-missing-feed-configuration) - C# project(s) are missing feed configuration

> These all seem to be our files from the VMR bootstrap that don't resolve to no root `NuGet.config` file.

- [x] [eng/bootstrap/buildBootstrapPreviouslySB.csproj](https://github.com/dotnet/dotnet/blob/main/eng/bootstrap/buildBootstrapPreviouslySB.csproj)  
    https://github.com/dotnet/source-build/issues/3230
- [x] [test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj](https://github.com/dotnet/dotnet/blob/main/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj)  
    https://github.com/dotnet/source-build/issues/3230
- [x] [tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj](https://github.com/dotnet/dotnet/blob/main/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj)  
    https://github.com/dotnet/source-build/issues/3230
- [x] [tools-local/tasks/SourceBuild.MSBuildSdkResolver/SourceBuild.MSBuildSdkResolver.csproj](https://github.com/dotnet/dotnet/blob/main/tools-local/tasks/SourceBuild.MSBuildSdkResolver/SourceBuild.MSBuildSdkResolver.csproj)  
    https://github.com/dotnet/source-build/issues/3230

### ⚠️ [CFS0001](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/project-artemis/central-feed-services-cfs#1-cfs0001-cfs0002---nodejs-projects-are-missing-feed-configuration) - Node.js project(s) are missing feed configuration

> Missing `.npmrc` files

- [x] [aspnetcore/src/submodules/MessagePack-CSharp/src/MessagePack.UnityClient/Assets/RuntimeUnitTestToolkit/package.json](https://github.com/aspnet/MessagePack-CSharp/tree/fe9fa0834d18492eb229ff2923024af2c87553f8/src/MessagePack.UnityClient/Assets/RuntimeUnitTestToolkit/package.json)  
    *Issue to be created, I reached out to dougbu*
- [x] [aspnetcore/src/submodules/MessagePack-CSharp/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/package.json](https://github.com/aspnet/MessagePack-CSharp/tree/fe9fa0834d18492eb229ff2923024af2c87553f8/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/package.json)  
    *Issue to be created, I reached out to dougbu*
- [x] [aspnetcore/src/submodules/spa-templates/src/content/Angular-CSharp/ClientApp/package.json](https://github.com/dotnet/spa-templates/tree/57bf5a0a1bf5d55eb9efefa92dcff6f067d4bfb3/src/content/Angular-CSharp/ClientApp/package.json)  
    *Issue to be created, I reached out to dougbu*
- [x] [aspnetcore/src/submodules/spa-templates/src/content/React-CSharp/ClientApp/package.json](https://github.com/dotnet/spa-templates/tree/57bf5a0a1bf5d55eb9efefa92dcff6f067d4bfb3/src/content/React-CSharp/ClientApp/package.json)  
    *Issue to be created, I reached out to dougbu*

**Comment by premun** [comment]
Just for book-keeping, the variables used to suppress the scans are following:

- `cfsNPMWarnLevel: none`
- `cfsNugetWarnLevel: none`
- `myGetWarnLevel: none`
- `NuGetSecurityAnalysisWarningLevel: none`

**Comment by premun** [comment]
So, we've got the Source Build `NuGet.config` without a root config fixed.
We also fixed the `source-build-externals` ones by cloaking them from the VMR.

I have also dismissed all of the multi-feed AzDO alerts based on https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/843/SingleFeedFAQ

**Comment by premun** [comment]
@brettfo we are seeing an alert in the VMR for this file: [fsharp/tests/FSharp.Build.UnitTests/NuGet.Config](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_git/ddda0dd6-918f-48ba-ba8f-730d9d8c9320?path=%2Fsrc%2Ffsharp%2Ftests%2FFSharp.Build.UnitTests%2FNuGet.Config&_a=annotate) which is synchronized from the `fsharp` repo.

I checked the history of the `dotnet-fsharp` repo and the alert was possibly suppressed wrongly. I can see a number of suppressed alerts in CG due to the multi-feed configuration which CG wrongly detects for our repos where we reference several public AzDO feeds with no upstreams (https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/843/SingleFeedFAQ). These suppressions are in place and the right step.
However, this linked one I think is not of the same kind. This one is probably missing the `<clear />` statement so it's a valid alert and should be resolved differently. I propose reinstating the alert and fixing the `NuGet.config` file which will in turn fix this in the VMR.

**Comment by premun** [comment]
> @brettfo we are seeing an alert in the VMR for this file: [fsharp/tests/FSharp.Build.UnitTests/NuGet.Config](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_git/ddda0dd6-918f-48ba-ba8f-730d9d8c9320?path=%2Fsrc%2Ffsharp%2Ftests%2FFSharp.Build.UnitTests%2FNuGet.Config&_a=annotate) which is synchronized from the fsharp repo.

Ah, so it seems that we are probably fine to dismiss this as the root NuGet.config should be enough to functionally match copying the required feeds into the offending config.

**Comment by premun** [comment]
All critical and high alerts have been resolved so I am closing this now.

I have also set up a weekly email that I get with a report of CG alerts for the VMR.
