### ISSUE TITLE
Tracking release pipeline issues

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3460]
This is a tracking issue for everything related to the release pipeline.

The issues can be divided up into the following categories:

* happy-path: Issues affecting the normal operation of the pipeline.
* validation: Issues affecting the validation executed by the pipeline that ensures things have the expected state.
* idempotency: It's often necessary to run the pipeline, or a portion of it, multiple times. For portions of the logic which had already been executed previously, there should be no negative affects.
* dry-run: Issues affecting the operation of the pipeline in dry run mode.
* testability: The pipeline itself should be testable to ensure its correctness.
* output: Features related to the output produced by the pipeline.

The issues below are listed in priority order:

- [x] [happy-path] Update Versions.props
  - [x] 8.0: https://github.com/dotnet/source-build/issues/3344
  - [x] 7.0: https://github.com/dotnet/source-build/issues/3385
- [x] #3447
      [happy-path]
- [x] #3444
      [happy-path]
- [x] #3449
      [idempotency]
- [x] #3450
      [idempotency]
- [x] #3387
      [testability]
- [x] #3443
      [validation]
- [x] #3415
      [dry-run]
- [x] #3265
      [output]
- [x] #3196
      [output]
- [x] #3058
      [validation]
- [x] #3297
      [validation]

The following issues are time-based, meaning that they need to be done at a certain point in the release cycle and so they don't fit into the prioritized list above:
- [ ] https://github.com/dotnet/source-build/issues/3304
      [output]
