### ISSUE TITLE
[VMR] Linux Vertical Build PoC

### ISSUE THREAD

**Issue by steveisok** [dotnet/source-build#3699]
## Objective

As part of https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/UB-Roadmap.md, we want to produce vertical builds for linux-x64 and linux-arm64 in order to flush out any problematic areas and continue to shape our VMR approach for .NET 9.

## Outcomes

- [ ] The PoC can produce the customer facing artifacts that .NET produces in its current official build (**or** we know we can produce such an artifact by completing a specified set of work).
- [ ] Issues are filed providing a clear path between the PoC and productization of the VMR vertical
- [ ] A rolling CI leg is added to the VMR to identify breaks in the PoC

# Work Items

- [ ] https://github.com/dotnet/source-build/issues/3654
- [ ] https://github.com/dotnet/source-build/issues/3671 - in order to target arm64 and other architectures different from the build host
- [ ] Build linux-x64
- [ ] Build linux-arm64
- [ ] Build linux-arm
- [ ] Add CI legs for linux-x64, linux-arm, and linux-arm64

**Comment by mmitche** [comment]
@steveisok Can we close this out at this point?

**Comment by tkapin** [comment]
Closing as agreed with @steveisok
