### ISSUE TITLE
[VMR] Mac Vertical Build PoC

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3705]
## Objective

As part of https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/UB-Roadmap.md, we want to produce vertical build(s) for Mac and iOS in order to flush out any problematic areas and continue to shape our VMR approach for .NET 9.

## Outcomes

- [ ] The PoC can produce the customer facing artifacts that .NET produces in its current official build (**or** we know we can produce such an artifact by completing a specified set of work).
- [ ] Issues are filed providing a clear path between the PoC and productization of the VMR vertical
- [ ] A rolling CI leg is added to the VMR to identify breaks in the PoC

# Work Items

**Comment by tkapin** [comment]
Closing as agreed with @steveisok
