### ISSUE TITLE
Signing support for VMR builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3708]
Products that Microsoft ships must be signed, of course.

We sign in a number of ways today:
- Post-build signing (signing in staging). This includes
  - Signing of most binaries in 6.0
  - Signing and notarization of Mac binaries in staging (all versions)
  - Signing of Linux installers in staging (all versions)
- Signing in-build (7.0 and 8.0, plus some repos in 6.0)
- Signing the DAC during the runtime build.

Some of the multiple ways of post-build signing have been driven by technical limitations. Linux and Mac signing could not occur within the same infra as typical MIcrobuild signing infra.

We need to work on improving this for the 9.0 VMR builds.

## Objectives

- Signing is simpler, and in alignment with the Vertical build philosophies. Few machines, if any. They **may** be on separate machines as required by infra limitations (e.g. must sign mac on a mac?)
- We still sign the DAC in build.
- We need not sign every build (aside from DAC, which is critical for debugging)
- Signing infra should be aligned across platforms. Right now we have 3-4 different technologies.

# Depends On

- [x] dotnet/source-build#3933

# Work Items

- [x] dotnet/arcade#14430
- [x] dotnet/arcade#15046
- [x] dotnet/arcade#14431
- [x] dotnet/arcade#15181
- [x] dotnet/arcade#15117
- [x] dotnet/arcade#14432
- [x] dotnet/arcade#14433
- [x] dotnet/arcade#14434
- [x] dotnet/arcade#14435
- [x] dotnet/arcade#14436
- [x] dotnet/arcade#14437
- [x] dotnet/arcade#14438
- [x] dotnet/arcade#15132
- [x] dotnet/source-build#4062
- [x] dotnet/source-build#4064
- [x] dotnet/source-build#4063
- [x] dotnet/source-build#4065
- [x] dotnet/source-build#4066
- [x] dotnet/source-build#4067
- [x] dotnet/source-build#4068
- [x] https://github.com/dotnet/runtime/issues/108605
- [x] https://github.com/dotnet/arcade/issues/15143
- [x] dotnet/aspnetcore#58445
- [x] https://github.com/dotnet/source-build/issues/4678
- [x] dotnet/arcade/issues/15192
- [x] dotnet/source-build/issues/4685
- [x] dotnet/arcade/issues/15001
- [x] dotnet/arcade/issues/15219
- [x] dotnet/fsharp/issues/18011

**T-Shirt Size: XL**

**Comment by mmitche** [comment]
T-Shirt Size: XL

There is a lot to do here:
- Decide on a signing design (in-build after each repo builds, after-build?)
- Expand signing support to other platforms.

**Comment by mmitche** [comment]
https://microsoft-my.sharepoint.com/:w:/p/mmitche/ERcEQy4Xex9CpRyTiGx9HrkBqf4iGDjDjwSk98QsczcROw?e=I6sfYl contains the deisgn.

See the rough implementation plan in the doc for some more info, but it's important to recognize the independent tracks of work available here. This work is highly parallelizable. We can work on signtool support for different containers without actually being able to submit them for signing. Similarly, you can work on enabling signing infra in the vertical builds before you have the ability to sign all containers. The areas where there may be blocking issues are cases where support for unpacking a container requires running on a Mac or Linux machine, and we can't yet run SignTool on that machine.

**Comment by tkapin** [comment]
Matt is about to work on this, needs the aspnetcore build in the VMR as the prerequisite.
