### ISSUE TITLE
Join points and product parity

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3739]
It is highly likely that Microsoft's .NET build will need some kind of join point where outputs from multiple build environments are required to produce other outputs needed to ship to customers. Note: This is not an option for our Linux distro partners. Cases might include NuGet packages that have native assets from multiple OSs in them, for instance. We need to identify what this set of assets is, and how it will be built.

Requirements:
- Join point job(s) can be run in both the isolated repo build as well as the full VMR build. The idea here is that we should be able to validate the join without doing a full VMR build.
- Join point job(s) must be at the end of the full product build.
- Support VMR build graph depth of >= 2. The depth might only be two but infrastructure should support a deeper graph.

**T-Shirt Size: XL**

# Work Items

Infrastructure:
- [x] https://github.com/dotnet/source-build/issues/4215
- [x] https://github.com/dotnet/source-build/issues/4216
- [x] https://github.com/dotnet/source-build/issues/4217
- [x] https://github.com/dotnet/source-build/issues/4218
- [x] https://github.com/dotnet/arcade/pull/15098

Join points/product parity issues in repos:
- [x] https://github.com/dotnet/source-build/issues/4633
- [x] https://github.com/dotnet/source-build/issues/4114
- [x] https://github.com/dotnet/aspnetcore/issues/52884
- [x] https://github.com/dotnet/source-build/issues/3904
- [x] #4336
- [x] #4041
- [x] https://github.com/dotnet/source-build/issues/4631
- [x] https://github.com/dotnet/source-build/issues/4777

**Comment by mmitche** [comment]
T-Shirt Size: XL

I think there will be quite a lot of messiness to unpack here.
