### ISSUE TITLE
Tracking: Repos targeting .NET 9 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3770]
This is a tracking issue to identify which repos are currently onboarded to use .NET 9 SDK. This is necessary as a prerequisite to eventually have these repos produce packages that target `net9.0`.

Repos:

- [x] arcade: https://github.com/dotnet/arcade/issues/14261
- [ ] aspire
    - Uses `NetCurrent` for all builds - repo still on net8.0 arcade/sdk
- [x] aspnetcore
- [x] cecil
- [ ] command-line-api: https://github.com/dotnet/command-line-api/issues/2305
    - uses `NetCurrent` for source-build scenarios - repo still on net8.0 arcade/sdk
- [x] deployment-tools: https://github.com/dotnet/deployment-tools/issues/317
- [x] diagnostics: https://github.com/dotnet/diagnostics/issues/4421
- [x] emsdk
- [x] format
- [x] fsharp: https://github.com/dotnet/fsharp/issues/16379
- [x] installer
- [x] ~~msbuild: https://github.com/dotnet/msbuild/issues/9492~~ (staying on .NET 8 SDK/Arcade)
    - upgraded with https://github.com/dotnet/msbuild/pull/10484
- [x] nuget-client: https://github.com/NuGet/NuGet.Client/pull/5511
- [x] razor: https://github.com/dotnet/razor/issues/9659
- [x] roslyn: https://github.com/dotnet/roslyn/issues/71084
- [x] roslyn-analyzers: https://github.com/dotnet/roslyn-analyzers/issues/7066
- [x] runtime: https://github.com/dotnet/runtime/issues/95605
- [x] scenario-tests
- [x] sdk
- [x] source-build-externals
- [x] source-build-reference-packages
- [x] sourcelink: https://github.com/dotnet/sourcelink/issues/1152
- [x] symreader: https://github.com/dotnet/symreader/issues/299
- [x] templating
- [x] test-templates
- [x] vstest: https://github.com/microsoft/vstest/issues/4779
- [x] windowsdesktop
- [x] winforms
- [x] wpf
- [x] xdt: https://github.com/dotnet/xdt/issues/547

Related to:
* https://github.com/dotnet/arcade/pull/14108
* https://github.com/dotnet/source-build/issues/3663

**Comment by ViktorHofer** [comment]
We will hit this issue every year again and again. Maybe it would make sense for source-build to use a different SDK than what the non source build infrastructure uses? That would also help with issues like https://github.com/dotnet/runtime/issues/95022#issuecomment-1827826930

**Comment by mthalman** [comment]
Source build is already using a .NET 9 SDK to build the VMR. The main driver of getting all these repos onto the new SDK is so we can roll out this change: https://github.com/dotnet/arcade/pull/14108. Once that's been rolled out, then we can remove a bunch of source build patches: https://github.com/dotnet/source-build/issues/3663.

**Comment by ViktorHofer** [comment]
Why not change these properties now when building from source and make repositories use a .NET 9 SDK in their source build legs? We will hit this problem with every release and it would be good to come up with a pattern that works long-term.

**Comment by mthalman** [comment]
> make repositories use a .NET 9 SDK in their source build legs

How would that work? I thought this was all controlled by global.json whether it's for source build or not.

**Comment by ViktorHofer** [comment]
> How would that work? I thought this was all controlled by global.json whether it's for source build or not.

Isn't there an environment variable today that the host respects to specify a different global.json? If not, we should discuss if adding such a feature would be worthwhile.

**Comment by mthalman** [comment]
> Isn't there an environment variable today that the host respects to specify a different global.json? If not, we should discuss if adding such a feature would be worthwhile.

Not that I'm aware of. It's certainly not [documented](https://learn.microsoft.com/dotnet/core/tools/global-json). That's related to https://github.com/dotnet/source-build/issues/3169.

**Comment by ViktorHofer** [comment]
One possible solution would be to allow major version SDK rollforwards in the individual repos (that's a global.json setting) and then just download a newer SDK. We should be able to change the version that is restored as that is handled via Arcade.

**Comment by mthalman** [comment]
But regardless of what SDK is used for source build, the issue of rolling out https://github.com/dotnet/arcade/pull/14108 still exists. Not having that rolled out would mean we would need to have a bunch of source build conditions that explicitly set `NetCurrent` to `net9.0`. That's not a good solution either. Alternatively, you would iteratively rollout `net9.0` in Arcade by first setting `NetCurrent` in Arcade to `net9.0` only for source build. Then once repos have taken the new SDK, `NetCurrent` in Arcade can be upgraded with no conditions. Still seems like a lot of coordination.

**Comment by ViktorHofer** [comment]
>  templating (doesn't consume NetCurrent)

From the list in the top post. What does that mean? I see that they are using a 9.0 Arcade SDK and are currently targeting net8.0.

**Comment by ViktorHofer** [comment]
All the repos in the list above that don't intentionally stay on an older .NET SDK and Arcade SDK, now upgraded to .NET 9 and Arcade 9. I assume the remaining six repositories will update later around ~June/July when they stop dual-inserting. Except for command-line-api which doesn't dual-inserts but just doesn't want to use the .NET 9 SDK yet.

**Comment by MichaelSimons** [comment]
I am closing this as its usefulness is over.  There are two remaining repos (aspire and command-line-api) that don't utilize a net 9.0 SDK.  They both utilize `NetCurrent` so they are compatible with the product source-build.
