### ISSUE TITLE
Tracking: Repos using `Microsoft.SourceBuild.Intermediate` in Prebuilt Baseline

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3773]
Relates to: https://github.com/dotnet/source-build/issues/3010

- [x] arcade
- [x] aspnetcore
- [x] cecil
- [x] command-line-api
- [x] deployment-tools
- [x] diagnostics
- [x] emsdk
- [x] format
- [x] fsharp
- [x] installer
- [x] msbuild
- [x] razor
- [x] roslyn
- [x] roslyn-analyzers
- [x] runtime
- [x] sdk
- [x] scenario-tests
- [x] source-build-externals
- [x] source-build-reference-packages
- [x] sourcelink
- [x] symreader
- [x] templating
- [x] test-templates
- [x] vstest
