### ISSUE TITLE
Update existing control usages in repository inner builds.

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3949]
Update all inner repo builds to remove usages of the existing controls and switch to the new control set as defined in https://microsoft-my.sharepoint.com/:w:/p/mmitche/EdchH8A4okpOoKhkki1sJEYB0LyAaaCyX5_6A887gL744Q?e=mFsz70

### Repository tracking

- [x] https://github.com/dotnet/arcade/issues/10659
- [x] dotnet/aspire#1646
- [x] https://github.com/dotnet/aspnetcore/issues/43637
- [x] dotnet/runtime#96908
- [x] https://github.com/dotnet/command-line-api/issues/1826
- [x] https://github.com/dotnet/deployment-tools/issues/216
- [x] https://github.com/dotnet/diagnostics/issues/3331
- [x] dotnet/runtime#96909
- [x] https://github.com/dotnet/format/issues/1701
- [x] https://github.com/dotnet/fsharp/issues/13812
- [x] https://github.com/dotnet/installer/issues/14418
- [x] https://github.com/dotnet/msbuild/issues/7925
- [x] https://github.com/NuGet/Home/issues/12063
- [x] https://github.com/dotnet/razor/issues/7078
- [x] https://github.com/dotnet/roslyn/issues/63667
- [x] https://github.com/dotnet/roslyn-analyzers/issues/6135
- [x] https://github.com/dotnet/runtime/issues/74819
- [x] dotnet/scenario-tests#60
- [x] https://github.com/dotnet/sdk/issues/27562
- [x] dotnet/source-build#3956
- [x] dotnet/source-build#3957
- [x] https://github.com/dotnet/sourcelink/issues/866
- [x] https://github.com/dotnet/symreader/issues/265
- [x] https://github.com/dotnet/templating/issues/5179
- [x] https://github.com/dotnet/test-templates/issues/246
- [x] https://github.com/microsoft/vstest/issues/3983
- [x] dotnet/windowsdesktop#4071
- [x] dotnet/winforms#10650
- [x] dotnet/wpf#8680
- [x] https://github.com/dotnet/xdt/issues/462

**Comment by mmitche** [comment]
Complete. Still waiting for some last minute flow but should be good.
