### ISSUE TITLE
Re-enable RHEL CI (including offline)

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#415]
We are using CentOS CI as a proxy for RHEL but we should get the infra setup for RHEL 7.5.

To be license compliant (while using Docker) we need a RHEL 7.5 host to build the image, to push to a private registry, and a RHEL 7.5 host to pull and run the image.

---

* [ ] Provision VSTS CI with RHEL 7.5: https://github.com/dotnet/core-eng/issues/3908
  * Docker, Git installed
* [x] Set up VSTS to pull the image from ACR and run legs with the YAML build.
* [ ] Ensure some notification is set up so we know when the VSTS CI breaks. (This isn't GitHub PR CI!)
* [x] Docker image:
  * [x] Get broken VSTS RHEL ~7.5~ 7.4 agent back up to build Dockerfiles.
    * [x] Git PATH, figure out nested Docker: https://github.com/dotnet/core-eng/issues/3906
    * [x] Red Hat subscription: https://github.com/dotnet/core-eng/issues/3921
  * [x] Add RHEL 7.5-based Dockerfile in https://github.com/dotnet/dotnet-buildtools-prereqs-docker
  * [x] Build the image using image-builder and push to ACR

Once this is set up, the VSTS RHEL7.5 CI can also be considered the official build.

**Comment by dleeapho** [comment]
Investigating prereqs Dockerfile https://github.com/dotnet/source-build/issues/520

**Comment by dagood** [comment]
Currently my plan is to try to use [yamlgettingstarted-containers.md](https://github.com/Microsoft/vsts-agent/blob/a022cdf52e6b2574d423b5a71aa339e4450d5a53/docs/preview/yamlgettingstarted-containers.md) with dotnet VSTS public CI once I have the images being built and published to our ACR (Azure Container Registry). VSTS yaml already supports getting the RHEL container from a private registry, which there isn't a clear way to do in our dotnet Jenkins.

**Comment by dagood** [comment]
This is now blocked on getting a sufficient number of up to date agents in the right VSTS instance: https://github.com/dotnet/core-eng/issues/3908 (FR).

**Comment by dagood** [comment]
We no longer plan to test on Red Hat, the value doesn't seem to be worth the infra implementation and ongoing maintenance. See https://github.com/dotnet/source-build/issues/677.
