### ISSUE TITLE
Ship a source-buildable .NET Core 2.1 RC

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#421]
We will deliver a high-quality RC source-build that moves predictably to RTW.

To do so, we need to:
- [x] maintain close sync with prodcon builds during RC (SHA syncing), ensuring offline builds are green.
- [x] ensure the behaviour gaps between the Microsoft distributed product are reduced and of minimal impact to consumers of source-build.
- [x] hold the line on using SDK 2.1.300 as the toolset to build the RC source-build
- [x] opportunistically, we will improve the engineering of source-build by removing patches.

**Comment by weshaggard** [comment]
The CLI version should be 2.1.300-preview2-008530 which is what we shipped for preview2.

**Comment by shawnro** [comment]
@dleeapho Are any of the "done criteria" able to be marked as complete?  I'm providing an update today and want to have an up-to-date status on these.

**Comment by dleeapho** [comment]
@shawnro this epic is currently in-flight.

**Comment by dleeapho** [comment]
Released as tag `v2.1.0-rc1` https://github.com/dotnet/source-build/tree/v2.1.0-rc1
