### ISSUE TITLE
Ship a source-buildable .NET Core 2.1 RTW

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#491]
We will deliver a high-quality RTW source-build that is servicable.

To do so, we need to:
- [x] maintain close sync with prodcon builds during RC (SHA syncing), ensuring offline builds are green.
- [ ] ensure the behaviour gaps between the Microsoft distributed product are reduced and of minimal impact to consumers of source-build.
- [ ] hold the line on using RC SDK 2.1.300 as the toolset to build the RTW source-build
- [ ] opportunistically, we will improve the engineering of source-build by removing patches.

Submodule repo blocking issues/prs:

- [x] https://github.com/dotnet/cli/issues/9176
- [x] https://github.com/dotnet/cli/pull/9187
- [x] https://github.com/dotnet/source-build/pull/498 --remove CLI patch 0005

Addresses disabling aspnetcore shared fx and bundled tools
- [x] https://github.com/dotnet/cli/pull/9178
- [x] https://github.com/aspnet/Universe/pull/1130

Netcore.app issue in smoke-test
- [x] https://github.com/dotnet/coreclr/pull/17846
- [x] https://github.com/dotnet/corefx/pull/29418

Repo-toolset update
- [x] https://github.com/Microsoft/msbuild/pull/3243
