### ISSUE TITLE
Source-build supports ARM64

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#750]
ARM64 is the emerging first architecture to tackle. Fedora and RHEL both have ARM64 as primary architectures:

- [x] Acquire ARM64 hardware
- [x] Build source-build on ARM64 machines
- [x] Add ARM64 machines to an internal agent pool
- [ ] Update internal CI to run ARM64 jobs
- [ ] Conform to distro build guidelines
    - [ ] Build with distro versions of .NET SDK
    - [ ] Do native bootstrapping with native ARM64

**Comment by omajid** [comment]
Just for clarification, is this arm32 or arm64 (aka aarch64)? Or both?

**Comment by wfurt** [comment]
would there be a reason to do one but not the other? I would think they would be pretty similar.

**Comment by dagood** [comment]
@deinok If you get ZenHub, you should be able to see the issues that are part of this epic, https://github.com/dotnet/source-build/issues/655 and https://github.com/dotnet/source-build/issues/699 (as of writing).

**Comment by deinok** [comment]
@dagood About the Yocto issue, I think that the issue requires this first to be solved.
Yocto is just a toolchain to join multiple packages. The hipotetic `meta-dotnet` should use `source-build` to orchestate the compilation of the Yocto layers.
Here you have the `meta-mono` layer to take it as an example (http://git.yoctoproject.org/cgit/cgit.cgi/meta-mono).

**Comment by dagood** [comment]
Thanks for the clarification. I think an issue can be in an epic for other reasons than a done dependency--like maybe it still makes sense to track as part of this effort since it's a way to prove out that source-build ARM support is working well enough for people to use. @dseefeld, PTAL, maybe add a done condition to the description?

This epic also isn't broken down yet. I'd expect issues for things like adding ARM CI to be filed once we start working on this.

**Comment by deinok** [comment]
Just one question @dagood, I feel like there are efforts to have runtime and SDK for x86 and ARM ready for 3.0.0. I'm right?

**Comment by tmds** [comment]
@dseefeld, does this issue cover building on an arm64 platform. Packaging guidelines may require this.

For example, https://fedoraproject.org/wiki/Architectures:

>  All builds have to happen in a native environment. this means cross compiling is not allowed, you can however use virtualisation to emulate your target system.

**Comment by dleeapho** [comment]
> I feel like there are efforts to have runtime and SDK for x86 and ARM ready for 3.0.0. I'm right?

@deinok correct. Though ARM64 tarballs are currently available for the Microsoft distribution (ie non-source-built) the overall effort is to round out ARM64 support with packages etc.

> Packaging guidelines may require this.
@tmds Thanks for bringing this to our attention. What you say may help to bring up ARM64 priority for source-build.

I'm updating the description with more info. As we get to this work we will be more focused.
/cc @leecow

**Comment by omajid** [comment]
I was playing around with source-build (`master`) on arm64, and we use a .NET Core SDK 2.1.403 to build the buildtools. That fails on my arm64 box:

```
$ /home/omajid/source-build/Tools/dotnetcli/dotnet publish --no-restore /home/omajid/source-build/packages/microsoft.dotnet.buildtools/3.0.0-preview1-03406-03/lib/tool-runtime/project.csproj -f netcoreapp2.0 -o /home/omajid/source-build/Tools
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/omajid/source-build/Tools/dotnetcli/sdk/2.1.403/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/omajid/source-build/packages/microsoft.dotnet.buildtools/3.0.0-preview1-03406-03/lib/tool-runtime/project.csproj]
$ git rev-parse --short HEAD 
f864f9e
$ /home/omajid/source-build/Tools/dotnetcli/dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     rhel
 OS Version:  8
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /home/omajid/source-build/Tools/dotnetcli/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/home/omajid/source-build/Tools/dotnetcli/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.5 [/home/omajid/source-build/Tools/dotnetcli/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

Looking around, it looks like 2.x coreclr doesn't actually support arm64 (https://github.com/dotnet/coreclr/issues/19578) ?

**Comment by tmds** [comment]
arm64 support is for .net core 3.0. This issue tracks that: https://github.com/dotnet/announcements/issues/82

**Comment by omajid** [comment]
Yeah, but source-build download the 2.1.403 SDK. I guess we will switch to a more recent buildtools/dotnet cli as we get closer to r3.0 elease?

**Comment by wfurt** [comment]
That is problematic and brings lot of other issues. I think the correct answer for now is to cross-compile. 

I know for sure that corefx will not build on arm as not all dependencies are ARM safe or available. This is more than just the SDK.

**Comment by tmds** [comment]
We need 1 arm sdk (which could be cross-compiled) to use as the bootstrap sdk.

> I know for sure that corefx will not build on arm as not all dependencies are ARM safe or available. This is more than just the SDK.

Can you be more specific? My expectation for Fedora (which could be wrong) is, we have the same packages available to compile corefx for arm64 as we do for x64.

**Comment by dleeapho** [comment]
Moving this the Future milestone since we are concentrating on prebuilt and patch hygiene on x64 in the 3.0 milestone.

**Comment by omajid** [comment]
I got source-build to build on arm64 here: https://github.com/dotnet/source-build/pull/1300

**Comment by dleeapho** [comment]
I'm setting up the milestone to 5.0 so we can move on getting CI running for ARM64 to ensure #1300 going forward. Let's figure what machines we can use (can we use existing Centriq servers), how many we need, the AzDo agent support that is required etc.

@crummel please liaise with @ilyas1974

**Comment by MichaelSimons** [comment]
[Triage] Arm64 is officially supported by source-build.  Closing.
